"""Add type column to lists

Revision ID: 3aff777aa8cc
Revises: 1283c124f4f2
Create Date: 2025-12-23 04:55:53.853070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3aff777aa8cc'
down_revision: Union[str, None] = '1283c124f4f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo_lists', sa.Column('type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo_lists', 'type')
    # ### end Alembic commands ###
